language: ruby
cache: bundler
before_script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script: bundle exec rspec
services:
  - redis-server
env:
rvm:
  - 2.3.1
notifications:
  email: false
sudo: false
