language: ruby
cache: bundler
before_script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script: bundle exec rspec
services:
env:
rvm:
  - 2.1.5
notifications:
  email: false
