language: ruby
cache: bundler
before_install:
  - gem install bundler # Ensure Bundler 2.0 is on the system.
before_script:
  - gem update --system
  - gem install bundler
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script: bundle exec rspec
bundler_args: --local
services:
  - redis-server
env:
rvm:
  - 2.6.2
notifications:
  email: false
sudo: false
